-- Supabase schema for "AI for my inner circle".
-- Run this in Supabase SQL Editor.
--
-- Browser env should use:
-- VITE_SUPABASE_URL
-- VITE_SUPABASE_ANON_KEY
--
-- Do NOT expose SUPABASE_SERVICE_ROLE_KEY in the browser.

create table if not exists public.visitors (
  id bigint generated by default as identity primary key,
  visitor_id text not null unique,
  first_seen_at_ms bigint not null,
  last_seen_at_ms bigint not null,
  is_returning boolean not null default false,
  first_referrer text,
  first_utm jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  session_id text not null unique,
  visitor_id text not null,
  started_at_ms bigint not null,
  last_event_at_ms bigint not null,
  is_returning_visitor boolean not null default false,
  referrer text,
  viewport jsonb,
  user_agent text,
  completed boolean not null default false,
  whatsapp_cta_clicked boolean not null default false,
  share_clicked boolean not null default false,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.survey_responses (
  id bigint generated by default as identity primary key,
  session_id text not null unique,
  visitor_id text not null,
  name text,
  phone text,
  answers jsonb not null default '{}'::jsonb,
  readiness_bucket text,
  final_whatsapp_question text,
  completion_status text not null default 'partial'
    check (completion_status in ('partial', 'completed', 'whatsapp_cta_clicked')),
  whatsapp_cta_clicked_at_ms bigint,
  share_clicked_at_ms bigint,
  created_at_ms bigint not null default (extract(epoch from now()) * 1000)::bigint,
  updated_at_ms bigint not null,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  session_id text,
  event_name text not null,
  payload jsonb not null default '{}'::jsonb,
  url text,
  user_agent text,
  created_at_ms bigint not null,
  inserted_at timestamptz not null default now()
);

create index if not exists visitors_last_seen_idx
  on public.visitors (last_seen_at_ms desc);

create index if not exists sessions_visitor_id_idx
  on public.sessions (visitor_id);

create index if not exists sessions_last_event_idx
  on public.sessions (last_event_at_ms desc);

create index if not exists survey_responses_visitor_id_idx
  on public.survey_responses (visitor_id);

create index if not exists survey_responses_bucket_idx
  on public.survey_responses (readiness_bucket);

create index if not exists survey_responses_status_idx
  on public.survey_responses (completion_status);

create index if not exists analytics_events_visitor_id_idx
  on public.analytics_events (visitor_id);

create index if not exists analytics_events_session_id_idx
  on public.analytics_events (session_id);

create index if not exists analytics_events_event_name_idx
  on public.analytics_events (event_name);

create index if not exists analytics_events_inserted_at_idx
  on public.analytics_events (inserted_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists visitors_set_updated_at on public.visitors;
create trigger visitors_set_updated_at
before update on public.visitors
for each row execute function public.set_updated_at();

drop trigger if exists sessions_set_updated_at on public.sessions;
create trigger sessions_set_updated_at
before update on public.sessions
for each row execute function public.set_updated_at();

drop trigger if exists survey_responses_set_updated_at on public.survey_responses;
create trigger survey_responses_set_updated_at
before update on public.survey_responses
for each row execute function public.set_updated_at();

alter table public.visitors enable row level security;
alter table public.sessions enable row level security;
alter table public.survey_responses enable row level security;
alter table public.analytics_events enable row level security;

drop policy if exists "Allow anon visitor insert" on public.visitors;
create policy "Allow anon visitor insert"
  on public.visitors
  for insert
  to anon
  with check (true);

drop policy if exists "Allow anon visitor update" on public.visitors;
create policy "Allow anon visitor update"
  on public.visitors
  for update
  to anon
  using (true)
  with check (true);

drop policy if exists "Allow anon session insert" on public.sessions;
create policy "Allow anon session insert"
  on public.sessions
  for insert
  to anon
  with check (true);

drop policy if exists "Allow anon session update" on public.sessions;
create policy "Allow anon session update"
  on public.sessions
  for update
  to anon
  using (true)
  with check (true);

drop policy if exists "Allow anon survey response insert" on public.survey_responses;
create policy "Allow anon survey response insert"
  on public.survey_responses
  for insert
  to anon
  with check (true);

drop policy if exists "Allow anon survey response update" on public.survey_responses;
create policy "Allow anon survey response update"
  on public.survey_responses
  for update
  to anon
  using (true)
  with check (true);

drop policy if exists "Allow anon analytics inserts" on public.analytics_events;
create policy "Allow anon analytics inserts"
  on public.analytics_events
  for insert
  to anon
  with check (true);

-- Do not create anon SELECT policies unless you intentionally want browser users
-- to read analytics data. Use the Supabase dashboard or service-role key for reads.
